# Generated by Django 5.0.6 on 2024-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogimage',
            old_name='image_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='dogimage',
            name='breed',
        ),
        migrations.AddField(
            model_name='dogimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dogimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dogimage',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
